<?php
o2def::appvar("_area", "_o2alpha");
o2def::appvar("appdir", "path");
o2def::appvar("appname", "name");
o2def::appvar("archive_gateway", "conn_type");
o2def::appvar("main_x", "_o2number");
o2def::appvar("main_y", "_o2number");
o2def::appvar("menu_items", "_o2structure");
o2def::appvar("operations", "_o2structure");
o2def::appvar("prg_items", "_o2structure");
o2def::appvar("prgdir", "path");
o2def::appvar("rep_appvars", "path");
o2def::appvar("rep_datatypes", "path");
o2def::appvar("rep_menus", "path");
o2def::appvar("rep_servers", "path");
o2def::appvar("rep_tables", "path");
o2def::appvar("rep_viewmodels", "path");
o2def::appvar("status_bar1", "description");
o2def::appvar("status_bar2", "description");
o2def::appvar("status_bar3", "description");
o2def::appvar("usrdir", "path");
o2def::appvar("view_actions", "_o2structure");
?>
